include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    always_declare_return_types: error

linter:
  rules:
    unnecessary_await_in_return: true
    prefer_final_locals: true
    prefer_double_quotes: true
    avoid_unused_constructor_parameters: true
    always_declare_return_types: true
    depend_on_referenced_packages: false
